/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callback.employeeis.pages.module1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.callback.employeeis.components.Department;
import com.callback.employeeis.components.Popup;
import com.callback.employeeis.components.Event;

/**
 *
 * @author HAZIQ
 */
public class AddDepartment extends javax.swing.JFrame {
  private final Department department;
  private final DepartmentMenu menu;
  
  /**
   * Creates new form AddDepartment
   */
  public AddDepartment() {
    this.menu = new DepartmentMenu();
    this.department = new Department();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFrame1 = new javax.swing.JFrame();
    jPanel1 = new javax.swing.JPanel();
    addDepartBtn = new javax.swing.JButton();
    departNameTF = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    backBtn = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();

    javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
    jFrame1.getContentPane().setLayout(jFrame1Layout);
    jFrame1Layout.setHorizontalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame1Layout.setVerticalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Add Department");
    setBackground(new java.awt.Color(204, 204, 204));

    jPanel1.setBackground(new java.awt.Color(255, 204, 0));

    addDepartBtn.setBackground(new java.awt.Color(42, 42, 42));
    addDepartBtn.setText("Add");
    addDepartBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addDepartBtnActionPerformed(evt);
      }
    });

    departNameTF.setBackground(new java.awt.Color(196, 196, 196));
    departNameTF.setForeground(new java.awt.Color(0, 0, 0));
    departNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        departNameTFKeyPressed(evt);
      }
    });

    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("Department name");

    backBtn.setBackground(new java.awt.Color(42, 42, 42));
    backBtn.setText("Back");
    backBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backBtnActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Add Department");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(backBtn)
        .addContainerGap())
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(89, 89, 89)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addDepartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addComponent(departNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(39, 39, 39)))
        .addContainerGap(92, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(departNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(addDepartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(59, 59, 59)
        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public static void run() {
    java.awt.EventQueue.invokeLater(() -> {
      new AddDepartment().setVisible(true);
    });
  }
  
  private void addDepartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartBtnActionPerformed
    String departName = departNameTF.getText();
    
    try {
      if (department.checkDepartmentName(departName)) { 
        department.addDepartment(departName);
        Popup.setPopupInfo(rootPane, 
                "Department Successfully Added");
        
        menu.show();
        backBtnActionPerformed(null);
      } else {
        Popup.setPopupWarning(rootPane, 
                "Invalid Department Name");
      }
    } catch (SQLException ex) {
      Logger.getLogger(AddDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_addDepartBtnActionPerformed

  private void departNameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departNameTFKeyPressed
    if (Event.onEnter(evt)) {
      addDepartBtnActionPerformed(null);
    }
  }//GEN-LAST:event_departNameTFKeyPressed

  private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    menu.show();
    department.closeConnection();
    dispose();
  }//GEN-LAST:event_backBtnActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addDepartBtn;
  private javax.swing.JButton backBtn;
  private javax.swing.JTextField departNameTF;
  private javax.swing.JFrame jFrame1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
