/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callback.employeeis.pages.module1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.callback.employeeis.components.Department;
import com.callback.employeeis.components.Popup;
import com.callback.employeeis.components.Event;

/**
 *
 * @author HAZIQ
 */
public class AddDepartment extends javax.swing.JFrame {
  private final Department department = new Department();
  private final DepartmentMenu menu = new DepartmentMenu();
  
  /**
   * Creates new form AddDepartment
   */
  public AddDepartment() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFrame1 = new javax.swing.JFrame();
    departNameTF = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    addDepartBtn = new javax.swing.JButton();
    backBtn = new javax.swing.JButton();

    javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
    jFrame1.getContentPane().setLayout(jFrame1Layout);
    jFrame1Layout.setHorizontalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jFrame1Layout.setVerticalGroup(
      jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Add Department");
    setBackground(new java.awt.Color(204, 204, 204));

    departNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        departNameTFKeyPressed(evt);
      }
    });

    jLabel1.setText("Department name");

    addDepartBtn.setText("Add");
    addDepartBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addDepartBtnActionPerformed(evt);
      }
    });

    backBtn.setText("Back");
    backBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(72, 72, 72)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(addDepartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1)
          .addComponent(departNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(307, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(backBtn)
        .addGap(31, 31, 31))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(141, 141, 141)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(departNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(addDepartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
        .addComponent(backBtn)
        .addGap(27, 27, 27))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public static void run() {
    java.awt.EventQueue.invokeLater(() -> {
      new AddDepartment().setVisible(true);
    });
  }
  
  private void addDepartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartBtnActionPerformed
    String departName = departNameTF.getText();
    
    try {
      if (department.checkDepartmentName(departName)) { 
        department.addDepartment(departName);
        Popup.setPopupInfo(rootPane, 
                "Department Successfully Added");
        
        menu.show();
        dispose();
      } else {
        Popup.setPopupWarning(rootPane, 
                "Invalid Department Name");
      }
    } catch (SQLException ex) {
      Logger.getLogger(AddDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_addDepartBtnActionPerformed

  private void departNameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departNameTFKeyPressed
    if (Event.onEnter(evt)) {
      addDepartBtnActionPerformed(null);
    }
  }//GEN-LAST:event_departNameTFKeyPressed

  private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    menu.show();
    dispose();
  }//GEN-LAST:event_backBtnActionPerformed
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addDepartBtn;
  private javax.swing.JButton backBtn;
  private javax.swing.JTextField departNameTF;
  private javax.swing.JFrame jFrame1;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
