/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callback.employeeis.pages.module1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.callback.employeeis.components.Department;
import com.callback.employeeis.components.Popup;
import com.callback.employeeis.components.Event;

/**
 *
 * @author HAZIQ
 */
public class UpdateDepartment extends javax.swing.JFrame {
  private final Department department;
  private final DepartmentMenu menu;
  private int departmentCodeInput;
  
  /**
   * Creates new form UpdateDepartment
   */
  public UpdateDepartment() {
    this.menu = new DepartmentMenu();
    this.department = new Department();
    initComponents();
    jPanel1.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    searchDepartmentCode = new javax.swing.JTextField();
    searchBtn = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    updateDeparmentName = new javax.swing.JTextField();
    updateBtn = new javax.swing.JButton();
    backBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Update Department");

    jPanel2.setBackground(new java.awt.Color(255, 204, 0));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Update Department");

    searchDepartmentCode.setBackground(new java.awt.Color(218, 218, 218));
    searchDepartmentCode.setForeground(new java.awt.Color(0, 0, 0));
    searchDepartmentCode.setText("Search for deparment code...");
    searchDepartmentCode.setToolTipText("Search for department code...");
    searchDepartmentCode.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        searchDepartmentCodeMouseClicked(evt);
      }
    });
    searchDepartmentCode.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        searchDepartmentCodeKeyPressed(evt);
      }
    });

    searchBtn.setBackground(new java.awt.Color(47, 47, 47));
    searchBtn.setText("Search");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(255, 204, 0));

    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("Department Name");

    updateDeparmentName.setBackground(new java.awt.Color(218, 218, 218));
    updateDeparmentName.setForeground(new java.awt.Color(0, 0, 0));
    updateDeparmentName.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        updateDeparmentNameKeyPressed(evt);
      }
    });

    updateBtn.setBackground(new java.awt.Color(47, 47, 47));
    updateBtn.setText("Update");
    updateBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(updateDeparmentName)
      .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(updateDeparmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(22, Short.MAX_VALUE))
    );

    backBtn.setBackground(new java.awt.Color(47, 47, 47));
    backBtn.setText("Back");
    backBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(107, 107, 107)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(searchDepartmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(searchBtn))))
        .addContainerGap(107, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(backBtn)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchDepartmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   *
   */
  public static void run() {	
    java.awt.EventQueue.invokeLater(() -> {	
      new UpdateDepartment().setVisible(true);	
    });	
  }
  
  private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    // TODO: check code department
    String result = null;
    departmentCodeInput = Integer.parseInt(searchDepartmentCode.getText());
    
    try {
      result = department.getDepartmentName(departmentCodeInput);
      
      if (result != null) {
        jPanel1.setVisible(true);
        updateDeparmentName.setText(result);
      } else {
        jPanel1.setVisible(false);
        Popup.setPopupError(rootPane, 
                "Department not found. Please enter again");
      }
    } catch (SQLException ex) {
      Logger.getLogger(UpdateDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_searchBtnActionPerformed

  private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    String departName = updateDeparmentName.getText();
    
    try {
      if (department.checkDepartmentName(departName)) { 
        department.addDepartment(departName);
        Popup.setPopupInfo(rootPane, 
                "Department Name Successfully Updated");
        
        menu.show();
        backBtnActionPerformed(null);
      } else {
        Popup.setPopupWarning(rootPane, 
                "Invalid Department Name");
      }
    } catch (SQLException ex) {
      Logger.getLogger(UpdateDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_updateBtnActionPerformed

  private void searchDepartmentCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDepartmentCodeMouseClicked
    searchDepartmentCode.setText("");
  }//GEN-LAST:event_searchDepartmentCodeMouseClicked

  private void searchDepartmentCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDepartmentCodeKeyPressed
    if (Event.onEnter(evt)) {
      searchBtnActionPerformed(null);
    }
  }//GEN-LAST:event_searchDepartmentCodeKeyPressed

  private void updateDeparmentNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateDeparmentNameKeyPressed
    if (Event.onEnter(evt)) {
      updateBtnActionPerformed(null);
    }
  }//GEN-LAST:event_updateDeparmentNameKeyPressed

  private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    menu.show();
    department.closeConnection();
    dispose();
  }//GEN-LAST:event_backBtnActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton searchBtn;
  private javax.swing.JTextField searchDepartmentCode;
  private javax.swing.JButton updateBtn;
  private javax.swing.JTextField updateDeparmentName;
  // End of variables declaration//GEN-END:variables
}
