/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callback.employeeis.pages;

import com.callback.employeeis.pages.module1.DepartmentMenu;
//import com.callback.employeeis.pages.module2.EmployeeMenu;
import com.callback.employeeis.pages.module3.Telephone_Directory_Maintenance;
import com.callback.employeeis.pages.module4.fram1;

/**
 *
 * @author HAZIQ
 */
public class MainMenu extends javax.swing.JFrame {
//  private EmployeeMenu employeMenu;
  private Telephone_Directory_Maintenance telephoneMenu;
  private fram1 reportMenu;
  
  /**
   * Creates new form MainMenu
   */
  public MainMenu() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    departmentBtn = new javax.swing.JButton();
    telephoneBtn = new javax.swing.JButton();
    reportBtn = new javax.swing.JButton();
    employeeBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Employee Information System");

    departmentBtn.setText("Department Maintenance");
    departmentBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        departmentBtnActionPerformed(evt);
      }
    });

    telephoneBtn.setText("Telephone Directory Maintenance");
    telephoneBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        telephoneBtnActionPerformed(evt);
      }
    });

    reportBtn.setText("Report");
    reportBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        reportBtnActionPerformed(evt);
      }
    });

    employeeBtn.setText("Employee Maintenance");
    employeeBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        employeeBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(120, 120, 120)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(employeeBtn)
          .addComponent(reportBtn)
          .addComponent(telephoneBtn)
          .addComponent(departmentBtn)
          .addComponent(jLabel1))
        .addContainerGap(72, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jLabel1)
        .addGap(39, 39, 39)
        .addComponent(departmentBtn)
        .addGap(18, 18, 18)
        .addComponent(employeeBtn)
        .addGap(18, 18, 18)
        .addComponent(telephoneBtn)
        .addGap(18, 18, 18)
        .addComponent(reportBtn)
        .addContainerGap(76, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void departmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentBtnActionPerformed
    DepartmentMenu.run();
    dispose();
  }//GEN-LAST:event_departmentBtnActionPerformed

  private void telephoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneBtnActionPerformed
    telephoneMenu = new Telephone_Directory_Maintenance();
    telephoneMenu.show();
    dispose();
  }//GEN-LAST:event_telephoneBtnActionPerformed

  private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
    reportMenu = new fram1();
    reportMenu.show();
    dispose();
  }//GEN-LAST:event_reportBtnActionPerformed

  private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
//    employeMenu = new EmployeeMenu();
//    employeMenu.show();
    dispose();
  }//GEN-LAST:event_employeeBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void run() {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton departmentBtn;
  private javax.swing.JButton employeeBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton reportBtn;
  private javax.swing.JButton telephoneBtn;
  // End of variables declaration//GEN-END:variables
}
