/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callback.employeeis.pages;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import com.callback.employeeis.components.Department;
import com.callback.employeeis.components.Popup;
import com.callback.employeeis.components.Event;

/**
 *
 * @author HAZIQ
 */
public class UpdateDepartment extends javax.swing.JFrame {
  private Department department = new Department();
  private int departmentCodeInput;
  
  /**
   * Creates new form UpdateDepartment
   */
  public UpdateDepartment() {
    initComponents();
    jPanel1.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    searchDepartmentCode = new javax.swing.JTextField();
    searchBtn = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    updateDeparmentName = new javax.swing.JTextField();
    updateBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Update Department");
    setPreferredSize(new java.awt.Dimension(649, 391));

    searchDepartmentCode.setText("Search for deparment code...");
    searchDepartmentCode.setToolTipText("Search for department code...");
    searchDepartmentCode.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        searchDepartmentCodeMouseClicked(evt);
      }
    });
    searchDepartmentCode.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        searchDepartmentCodeKeyPressed(evt);
      }
    });

    searchBtn.setText("Search");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
      }
    });

    jLabel1.setText("Department Name");

    updateDeparmentName.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        updateDeparmentNameKeyPressed(evt);
      }
    });

    updateBtn.setText("Update");
    updateBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(updateDeparmentName)
      .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(updateDeparmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(22, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(68, 68, 68)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(searchDepartmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(searchBtn)))
        .addContainerGap(192, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(85, 85, 85)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchDepartmentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(31, 31, 31)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(48, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    // TODO: check code department
    String result = null;
    departmentCodeInput = Integer.parseInt(searchDepartmentCode.getText());
    
    try {
      result = department.getDepartmentName(departmentCodeInput);
      
      if (result != null) {
        jPanel1.setVisible(true);
        updateDeparmentName.setText(result);
      } else {
        jPanel1.setVisible(false);
        Popup.setPopupError(rootPane, 
                "Department not found. Please enter again");
      }
    } catch (SQLException ex) {
      Logger.getLogger(UpdateDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_searchBtnActionPerformed

  private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    String departName = updateDeparmentName.getText();
    
    try {
      if (department.checkDepartmentName(departName)) { 
        department.addDepartment(departName);
        Popup.setPopupInfo(rootPane, 
                "Department Name Successfully Updated");
        
        DepartmentMenu.run();
        setVisible(false);
      } else {
        Popup.setPopupWarning(rootPane, 
                "Invalid Department Name");
      }
    } catch (SQLException ex) {
      Logger.getLogger(UpdateDepartment.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_updateBtnActionPerformed

  private void searchDepartmentCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDepartmentCodeMouseClicked
    searchDepartmentCode.setText("");
  }//GEN-LAST:event_searchDepartmentCodeMouseClicked

  private void searchDepartmentCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDepartmentCodeKeyPressed
    if (Event.onEnter(evt)) {
      searchBtnActionPerformed(null);
    }
  }//GEN-LAST:event_searchDepartmentCodeKeyPressed

  private void updateDeparmentNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateDeparmentNameKeyPressed
    if (Event.onEnter(evt)) {
      updateBtnActionPerformed(null);
    }
  }//GEN-LAST:event_updateDeparmentNameKeyPressed

  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(UpdateDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(UpdateDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(UpdateDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(UpdateDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//  }
  
  public static void run() {
    java.awt.EventQueue.invokeLater(() -> {
      new UpdateDepartment().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton searchBtn;
  private javax.swing.JTextField searchDepartmentCode;
  private javax.swing.JButton updateBtn;
  private javax.swing.JTextField updateDeparmentName;
  // End of variables declaration//GEN-END:variables
}
